### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by 7LFB** [FabianHeinemann/Deep_learning_for_liver_NAS_and_fibrosis_scoring#2]
@FabianHeinemann 

As mentioned in the paper, ' Liver sections were assigned to discrete scores quantifying the histopathological features of ballooning (0–2), inflammation (0–3) '.
But the dataset only contain ballooning (0-1, ignore), inflammation (0–2, ignore) .  It is not consistent.

**Comment by FabianHeinemann** [comment]
@7LFB: Let me clarify.

This is a misunderstanding caused by the following: the classes _per tile_ are different than the aggregated scores _per liver_.

**Classes per tile (see Fig 2 of paper):**
- Ballooning: 0, 1, ignore
- Inflammation: 0, 1, 2, ignore
- Steatosis: 0, 1, 2, 3, ignore
- Fibrosis: 0, 1, 2, 3, 4 ignore

Per liver these scores (the weighted sum of class values over the whole liver) are aggregated and mapped via thresholds to one score per liver (see Fig 5 of paper, see also Note [2]). This score per liver corresponds to the features of the Kleiner score, i.e.:

**Scores per liver [2]:**
- Ballooning: 0, 1, 2
- Steatosis: 0, 1, 2, 3
- Inflammation: 0, 1, 2, 3
- Fibrosis: 0, 1, 2, 3, 4

I hope this helped.

Best regards
Fabian

[1]: Steatosis liver score of 3 was not present our dataset.

[2]: The reason for this difference of per tile classes and liver scores is that in a number of cases (Ballooning and Inflammation) on a microscopic level (per tile) it was not possible find classes matching the value on the macroscopic scale (per liver). This was only possible by aggregation, since these features can be sparsely distributed.

**Comment by 7LFB** [comment]
> @7LFB: Let me clarify.
> 
> This is a misunderstanding caused by the following: the classes _per tile_ are different than the aggregated scores _per liver_.
> 
> **Classes per tile (see Fig 2 of paper):**
> 
> * Ballooning: 0, 1, ignore
> * Inflammation: 0, 1, 2, ignore
> * Steatosis: 0, 1, 2, 3, ignore
> * Fibrosis: 0, 1, 2, 3, 4 ignore
> 
> Per liver these scores (the weighted sum of class values over the whole liver) are aggregated and mapped via thresholds to one score per liver (see Fig 5 of paper). This score per liver corresponds to the features of the Kleiner score, i.e.:
> 
> **Scores per liver:**
> 
> * Ballooning: 0, 1, 2
> * Steatosis: 0, 1, 2, 3
> * Inflammation: 0, 1, 2, 3
> * Fibrosis: 0, 1, 2, 3, 4
> 
> Note: Steatosis liver score of 3 was not present our dataset.
> 
> I hope this helped.
> 
> Best regards
> Fabian

Yep. I see. Thanks a lot.
