### ISSUE TITLE
file name rules

### ISSUE THREAD

**Issue by 7LFB** [FabianHeinemann/Deep_learning_for_liver_NAS_and_fibrosis_scoring#3]
Could you please further explain how each file is named? What does the number in the file name mean？
1. for the image tiles in ballooning folder, can we know whether it has other features (fibrosis, inflammation, steatosis) based on the name?
2. can we group the tiles to get the whole slide image based on the file name?

Thanks. @FabianHeinemann

**Comment by FabianHeinemann** [comment]
Hi 7LFB,

1. No. Actually it is important that other features are not correlated, otherwise you can get wrong predictions, since the CNN learns also the correlated features. E.g. ballooning cells for training should be shown with fibrosis and without.

But you can classify the images with the CNN to find other features.

2. The filename probably contains an Id (not relevant for you) and x and y, e.g. ID_id2_id3_xx_yy.png.  
With x and y you can reconstruct the picture easily. In fact the output csv. contains x and y and you can visualize plots like in the paper with software like Spotfire.

Hope that helped.

Best regards
Fabian

**Comment by 7LFB** [comment]
thanks a lot!
